-- AlterTable
ALTER TABLE "DailySaleItem" ADD COLUMN     "visitAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "DailySalePayment" ADD COLUMN     "visitAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
